# Generated by Django 5.0.6 on 2024-11-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('director', models.CharField(max_length=50)),
                ('imdb_rating', models.FloatField(max_length=2)),
                ('genre', models.ManyToManyField(related_name='movies', to='movie.genre')),
            ],
            options={
                'db_table': 'movies',
            },
        ),
    ]
